
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggleWrapper from "./ThemeToggleWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Le bouton ThemeToggle est déplacé dans un composant client séparé ThemeToggleClient.tsx

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <header className="w-full shadow-md border-b-4 border-red-700">
          <div className="max-w-3xl mx-auto flex items-center justify-between py-4 px-6">
            <a href="/" className="text-2xl font-extrabold tracking-tight" style={{color:'#b1001a'}}>Mon Blog Perso</a>
            <div className="flex items-center">
              <nav className="flex gap-6 text-lg font-bold">
                <a href="/" className="text-[#ff2a36] hover:text-white transition-colors">Accueil</a>
                <a href="/livre-dor" className="text-[#ff2a36] hover:text-white transition-colors">Livre d'or</a>
                <a href="/contact" className="text-[#ff2a36] hover:text-white transition-colors">Contact</a>
                <a href="/playlists" className="text-[#ff2a36] hover:text-white transition-colors">Playlists</a>
                <a href="/categories" className="text-[#ff2a36] hover:text-white transition-colors">Catégories</a>
              </nav>
              {/* Bouton thème dans un composant client */}
              <ThemeToggleWrapper />
            </div>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="w-full text-center py-6 mt-12 border-t border-red-700" style={{background:'#fff',color:'#ff2a36'}}>
          © {new Date().getFullYear()} - Blog personnel par Maxime
        </footer>
      </body>
    </html>
  );
}
