
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggleWrapper from "./ThemeToggleWrapper";
import CustomAudioPlayer from "../components/CustomAudioPlayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Le bouton ThemeToggle est déplacé dans un composant client séparé ThemeToggleClient.tsx

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <header className="w-full shadow-md border-b-4 border-red-700">
          <div className="max-w-3xl mx-auto flex items-center justify-between py-4 px-6">
            <a href="/" className="text-2xl font-extrabold tracking-tight" style={{color:'#b1001a'}}>Mon Blog Perso</a>
            <div className="flex items-center">
              <nav className="flex gap-6 text-lg font-bold">
                <a href="/" className="text-[#ff2a36] hover:text-white transition-colors">Accueil</a>
                <a href="/livre-dor" className="text-[#ff2a36] hover:text-white transition-colors">Livre d'or</a>
                <a href="/contact" className="text-[#ff2a36] hover:text-white transition-colors">Contact</a>
                <a href="/playlists" className="text-[#ff2a36] hover:text-white transition-colors">Playlists</a>
                <a href="/categories" className="text-[#ff2a36] hover:text-white transition-colors">Catégories</a>
              </nav>
              {/* Bouton thème dans un composant client */}
              <ThemeToggleWrapper />
            </div>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="w-full text-center py-6 mt-12 border-t border-red-700" style={{background:'#fff',color:'#ff2a36',position:'relative'}}>
          © {new Date().getFullYear()} - Blog personnel par Maxime<br />
          <span style={{display:'inline-flex',alignItems:'center',gap:'6px',flexWrap:'wrap'}}>
            <a href="https://twitter.com/maxlo425" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Twitter">
              <svg width="20" height="20" viewBox="0 0 24 24" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M24 4.557a9.93 9.93 0 0 1-2.828.775 4.932 4.932 0 0 0 2.165-2.724c-.951.564-2.005.974-3.127 1.195A4.92 4.92 0 0 0 16.616 3c-2.73 0-4.942 2.21-4.942 4.932 0 .386.045.763.127 1.124C7.728 8.89 4.1 7.13 1.671 4.149c-.423.722-.666 1.561-.666 2.475 0 1.708.87 3.216 2.188 4.099a4.904 4.904 0 0 1-2.237-.616c-.054 2.281 1.581 4.415 3.949 4.89a4.936 4.936 0 0 1-2.224.084c.627 1.956 2.444 3.377 4.6 3.417A9.867 9.867 0 0 1 0 21.543a13.94 13.94 0 0 0 7.548 2.209c9.057 0 14.009-7.496 14.009-13.986 0-.213-.005-.425-.014-.636A9.936 9.936 0 0 0 24 4.557z"/></svg>
              Twitter
            </a>
            <a href="https://tiktok.com/@maxlo245" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="TikTok">
              <svg width="20" height="20" viewBox="0 0 256 256" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M216.4 128.6a88.4 88.4 0 0 1-88.4 88.4c-48.8 0-88.4-39.6-88.4-88.4s39.6-88.4 88.4-88.4c48.8 0 88.4 39.6 88.4 88.4zm-88.4-72.4c-40 0-72.4 32.4-72.4 72.4s32.4 72.4 72.4 72.4 72.4-32.4 72.4-72.4-32.4-72.4-72.4-72.4zm36.8 72.4c0 20.3-16.5 36.8-36.8 36.8s-36.8-16.5-36.8-36.8 16.5-36.8 36.8-36.8 36.8 16.5 36.8 36.8z"/></svg>
              TikTok
            </a>
            <a href="https://open.spotify.com/user/vj763nyyje953ae9bpf1hzg7e" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Spotify">
              <svg width="20" height="20" viewBox="0 0 168 168" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><circle cx="84" cy="84" r="84"/><path fill="#fff" d="M120.1 116.2c-1.6 2.6-5 3.4-7.6 1.8-20.8-12.7-47-15.6-77.7-8.6-3 0.7-6-1.2-6.7-4.2-0.7-3 1.2-6 4.2-6.7 33.2-7.5 62.2-4.2 85.1 9.9 2.6 1.6 3.4 5 1.8 7.8zm10.9-21.7c-2 3.2-6.2 4.2-9.4 2.2-23.8-14.6-60.2-18.8-88.4-10.4-3.6 1-7.4-1-8.4-4.6-1-3.6 1-7.4 4.6-8.4 31.7-9.1 71.1-4.5 98.2 11.2 3.2 2 4.2 6.2 2.2 9.4zm11.2-23.2c-28.2-17.1-75.1-18.7-102.2-10.3-4.1 1.2-8.4-1.1-9.6-5.2-1.2-4.1 1.1-8.4 5.2-9.6 30.2-8.9 81.2-7.1 113.2 11.2 4 2.4 5.3 7.7 2.9 11.7-2.4 4-7.7 5.3-11.7 2.9z"/></svg>
              Spotify
            </a>
            <a href="https://instagram.com/maxime_larnt" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Instagram">
              <svg width="20" height="20" viewBox="0 0 448 512" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9 114.9-51.3 114.9-114.9-51.3-114.9-114.9-114.9zm0 186c-39.5 0-71.5-32-71.5-71.5s32-71.5 71.5-71.5 71.5 32 71.5 71.5-32 71.5-71.5 71.5zm146.4-194.3c0 14.9-12.1 27-27 27s-27-12.1-27-27 12.1-27 27-27 27 12.1 27 27zm76.1 27.2c-1.7-35.3-9.9-66.7-36.2-92.9C388.7 9.9 357.3 1.7 322 0 285.7-1.7 162.3-1.7 126 0 90.7 1.7 59.3 9.9 33.1 36.2 6.9 62.4-1.7 93.8 0 129.1c1.7 36.3 1.7 159.7 0 196-1.7 35.3 9.9 66.7 36.2 92.9 26.2 26.2 57.6 34.4 92.9 36.2 36.3 1.7 159.7 1.7 196 0 35.3-1.7 66.7-9.9 92.9-36.2 26.2-26.2 34.4-57.6 36.2-92.9 1.7-36.3 1.7-159.7 0-196zm-48.5 262c-7.8 19.6-22.9 34.7-42.5 42.5-29.4 11.7-99.2 9-132.5 9s-103.1 2.6-132.5-9c-19.6-7.8-34.7-22.9-42.5-42.5-11.7-29.4-9-99.2-9-132.5s-2.6-103.1 9-132.5c7.8-19.6 22.9-34.7 42.5-42.5 29.4-11.7 99.2-9 132.5-9s103.1-2.6 132.5 9c19.6 7.8 34.7 22.9 42.5 42.5 11.7 29.4 9 99.2 9 132.5s2.6 103.1-9 132.5z"/></svg>
              Instagram
            </a>
            <a href="https://discord.gg/RcdajSBECj" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Discord">
              <svg width="20" height="20" viewBox="0 0 71 55" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M60.104 4.552A58.36 58.36 0 0 0 46.852.8a.117.117 0 0 0-.123.06c-2.048 3.614-4.096 8.29-5.616 12.06-6.656-.99-13.312-.99-19.968 0-1.52-3.77-3.568-8.446-5.616-12.06A.117.117 0 0 0 15.148.8a58.36 58.36 0 0 0-13.252 3.752.105.105 0 0 0-.05.043C.356 9.06-.213 13.46.066 17.82c.01.14.12.28.26.32 6.788 2.13 13.34 5.24 19.5 9.44a.12.12 0 0 0 .13.01c1.52-1.14 3.04-2.29 4.52-3.43a.12.12 0 0 1 .14 0c1.48 1.14 3 2.29 4.52 3.43a.12.12 0 0 0 .13-.01c6.16-4.2 12.71-7.31 19.5-9.44a.12.12 0 0 0 .26-.32c.28-4.36-.29-8.76-1.83-13.225a.105.105 0 0 0-.05-.043z"/></svg>
              Discord
            </a>
            <a href="https://twitch.tv/maxlo425" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Twitch">
              <svg width="20" height="20" viewBox="0 0 512 512" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M80 0L0 96v416h144v96h96l96-96h96l96-96V0H80zm384 384h-96l-96 96v-96H80V96h384v288zm-64-160h-32v96h32v-96zm-96 0h-32v96h32v-96z"/></svg>
              Twitch
            </a>
            <a href="https://reddit.com/user/Key-Ask-3385/" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Reddit">
              <svg width="20" height="20" viewBox="0 0 512 512" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><circle cx="256" cy="256" r="256"/><ellipse fill="#fff" cx="256" cy="256" rx="192" ry="128"/><circle fill="#ff4500" cx="176" cy="256" r="32"/><circle fill="#ff4500" cx="336" cy="256" r="32"/><ellipse fill="#fff" cx="256" cy="320" rx="80" ry="32"/></svg>
              Reddit
            </a>
            <a href="https://github.com/maxlo245" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="GitHub">
              <svg width="20" height="20" viewBox="0 0 24 24" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.387.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.415-4.042-1.415-.546-1.387-1.333-1.757-1.333-1.757-1.089-.745.084-.729.084-.729 1.205.084 1.84 1.236 1.84 1.236 1.07 1.834 2.809 1.304 3.495.997.108-.775.418-1.305.762-1.605-2.665-.305-5.466-1.334-5.466-5.93 0-1.31.469-2.381 1.236-3.221-.124-.303-.535-1.523.117-3.176 0 0 1.008-.322 3.301 1.23a11.52 11.52 0 0 1 3.003-.404c1.018.005 2.045.138 3.003.404 2.291-1.553 3.297-1.23 3.297-1.23.653 1.653.242 2.873.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.803 5.624-5.475 5.921.43.372.823 1.102.823 2.222 0 1.606-.015 2.898-.015 3.293 0 .322.216.694.825.576C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
              GitHub
            </a>
            <a href="https://ko-fi.com/maxlo24" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Ko-fi">
              <svg width="20" height="20" viewBox="0 0 512 512" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><path d="M477.5 186.5c-13.5-13.5-31.5-21-50.5-21H80c-44.2 0-80 35.8-80 80s35.8 80 80 80h347c19 0 37-7.5 50.5-21 13.5-13.5 21-31.5 21-50.5s-7.5-37-21-50.5zM80 306c-22.1 0-40-17.9-40-40s17.9-40 40-40h347c22.1 0 40 17.9 40 40s-17.9 40-40 40H80z"/></svg>
              Ko-fi
            </a>
            <a href="https://patreon.com/u66868989" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="Patreon">
              <svg width="20" height="20" viewBox="0 0 24 24" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><circle cx="17.5" cy="6.5" r="6.5"/><rect x="1" y="1" width="6" height="22" rx="3"/></svg>
              Patreon
            </a>
            <a href="https://stats.fm/metalindustrial" target="_blank" rel="noopener noreferrer" style={{color:'#ff2a36',marginRight:'10px',display:'inline-flex',alignItems:'center'}} aria-label="stats.fm">
              <svg width="20" height="20" viewBox="0 0 24 24" style={{marginRight:'4px',fill:'currentColor'}} xmlns="http://www.w3.org/2000/svg"><rect x="2" y="17" width="2" height="5"/><rect x="6" y="13" width="2" height="9"/><rect x="10" y="9" width="2" height="13"/><rect x="14" y="5" width="2" height="17"/><rect x="18" y="1" width="2" height="21"/></svg>
              stats.fm
            </a>
          </span>
          <div id="music-player" style={{position:'fixed',left:0,right:0,bottom:0,zIndex:50,background:'#181818',borderTop:'2px solid #ff2a36',padding:'8px 0'}}>
            <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:16}}>
              <CustomAudioPlayer />
              <div style={{display:'flex',justifyContent:'center',alignItems:'center',gap:32}}>
                {/* Spotify */}
                <iframe style={{borderRadius:12}} src="https://open.spotify.com/embed/playlist/06succq5Lndt6TcyplVAsn?utm_source=generator" width="340" height="400" frameBorder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
                {/* YouTube */}
                <iframe width="280" height="80" src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=EnSIkaIECMiOmarE&amp;controls=1" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen style={{borderRadius:12}}></iframe>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
